name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    if: ${{ vars.JIT_RUNNER_ENABLED == 'true' }}
    runs-on: [self-hosted, linux, x64, jit-runner]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_wrapper: false
      - run: make check
